### ISSUE TITLE
When executing all urls in the errors list

### ISSUE THREAD

**Issue by pte1601** [TobiasPankner/Fast-Yahoo-Ticker-Symbol-Downloader#1]
Hello Tobias

I am testing your script and I am getting this error:

Batch completed: 
	Took 0.414s  (0.005s per url)
	Total Errors: 76
	Total symbols: 0

I am using Python 3.9, PyCharm prof; Could you assist with this issue?

Thanks, Peter

**Comment by TobiasPankner** [comment]
Hello Peter,
what command exactly are you running to start the program?

**Comment by pte1601** [comment]
Hello Tobias
I just pasted your script into Pycharm and run it.
Greetings Peter

**Comment by TobiasPankner** [comment]
The correct way to run it is to save (or download) the .py file and then run it from cmd like in the readme.  
Please try that and get back to me.

**Comment by pte1601** [comment]
Hello Tobias
I just started the symbol_downloader.py from the command line with the same
failure result;
I limited to tickers to equity and etf
Greetings, Peter

Am Sa., 31. Juli 2021 um 21:03 Uhr schrieb TobiasPankner <
***@***.***>:

**Comment by TobiasPankner** [comment]
Please copy and paste the exact command so I can try it out.

**Comment by pte1601** [comment]
python symbol_downloader.py

Am So., 1. Aug. 2021 um 20:41 Uhr schrieb TobiasPankner <
***@***.***>:

**Comment by TobiasPankner** [comment]
Fixed with commit 7434f76  
Sorry for the long wait
