### ISSUE TITLE
Problem with constraint

### ISSUE THREAD

**Issue by RafaBarneto** [TobiasPankner/Fast-Yahoo-Ticker-Symbol-Downloader#2]
Hi Tobias,
I am trying to execute your script, but receive an error saying   
File "symbol_downloader.py", line 5, in <module>
    from constraint import Problem
ModuleNotFoundError: No module named 'constraint'

I installed python-constraint as required, but if I try to install just constraint, I get several errors.
I use Mac with macOS 11.5.2

On the other hand I would like to execute your program from another python program: it's possible?, how?
Thanks.

**Comment by TobiasPankner** [comment]
Hi,
please install the dependencies using the requirements file.  
`pip install -r requirements.txt`  
It's possible to execute the script from another python file. Take a look at [this](https://stackoverflow.com/questions/3781851/run-a-python-script-from-another-python-script-passing-in-arguments)

**Comment by RafaBarneto** [comment]
Thanks Tobias,

It takes 2.52 min. to download 121239 equity tickers. GREAT JOB!!!

**Comment by TobiasPankner** [comment]
You're welcome!
